name: MAIN

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: tar zcf hy_torrentleech.dlm INFO search.php
      - name: Release
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: hy_torrentleech.dlm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
